### ISSUE TITLE
Person Trip Analysis - Travel Related User Benefits

### ISSUE THREAD

**Issue by boz1** [matsim-vsp/matsim-analysis#5]
Dear Ihab,

Currently, I'm using the matsim-analysis tool to analyze my outputs from the Open Berlin Scenario. When you are calculating the travel related user benefits, you use the following code piece:

```
for (Person person : scenario.getPopulation().getPersons().values()) {
			personId2userBenefit.put(person.getId(), person.getSelectedPlan().getScore() / scenario.getConfig().planCalcScore().getMarginalUtilityOfMoney());
}
```

I'm now curious whether the marginal utility of money returned here is the same income dependent marg. util. of money assigned to each agent in open berlin scenario or is it the default value. If it is not the personalized marg. util. of money from the open berlin scenario, would it make sense to adapt the tool in such way?

Secondaly, can we think of the aggregated travel related user benefits value + toll revenues in the aggregated_info_for_each mode file as the **overall welfare change**?

Finally, can we say that the **vtts** calculated is non-heterogeneous since the used marginal utility of money is not agent specific?

Thanks, 
Burak

**Comment by ikaddoura** [comment]
question 1) this code piece only gets the marginal utility of money specified in the planCalcScore config group. So depending on how the marginal utility of money is implemented, this may only return the global marginal utility of money and not the person-specific one. So watch out and rather write your own analysis code!

question 2) yes, but make sure everything is converted correctly into utility units, and also note that there are different ways to compute user benefits, e.g. use the logsum term instead of the score sum of all selected plans

question 3) the VTTS is still heterogeneous since agents have different number of activities and experience a different time pressure.

**Comment by boz1** [comment]
Thanks for your answers. I'll then implement my own code for that matter (q1) and try different ways for computing user benefits (q2).
