### ISSUE TITLE
Intermodal tests

### ISSUE THREAD

**Issue by ghost** [matsim-vsp/matsim-analysis#7]
Hello,
In MatsimAnalysisRunIntermodalTest.java, what is the difference between test1 and test2?

Thank you.

**Comment by kt86** [comment]
Hi,
in test2, there is also another modes added: https://github.com/matsim-vsp/matsim-analysis/blob/96817c6ca6a3f03ce1c31d9dd89f2ca25e3a9610/src/test/java/org/matsim/analysis/MatsimAnalysisRunIntermodalTest.java#L110

and it uses a defined MainModeIdentifier https://github.com/matsim-vsp/matsim-analysis/blob/96817c6ca6a3f03ce1c31d9dd89f2ca25e3a9610/src/test/java/org/matsim/analysis/MatsimAnalysisRunIntermodalTest.java#L127


Maybe @vsp-gleich (?) can give you some more information?

**Comment by vsp-gleich** [comment]
Hi, like @kt86 pointed out the difference concerns only those two settings. To me it seems test1 checks what happens if no special intermodal AnalysisModeIdentifier is used and test2 checks what happens if special intermodal AnalysisModeIdentifier is used (that might return as a trip mode a mode that does not exist as leg mode).

**Comment by ghost** [comment]
Thank you!
